// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	COREPACK_INTEGRITY_KEYS: "0";
	NODE_VERSION: "20.18.0";
	PNPM_VERSION: "10.4.1";
	NEXTJS_ENV: string;
	ASSETS: Fetcher;
}
