# @ref: https://fly.io/docs/reference/configuration

app = "next-start"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 256
console_command = "/bin/sh"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    NODE_VERSION = "20"

[deploy]
  # https://fly.io/docs/apps/deploy/#deployment-strategy
  # Staging or Testing: `immediate` | Production: `bluegreen`
  strategy = "bluegreen"

[env]
  NODE_ENV = "production"
  HOSTNAME = "0.0.0.0"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [http_service.tls_options]
    alpn = ["h2", "http/1.1"]
    versions = ["TLSv1.2", "TLSv1.3"]
    default_self_signed = false

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = true
