app = "next-start"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  private_network = true
  allowed_public_ports = []
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"
  # release_command = "/usr/bin/npm run db:migrate"

[env]
  PORT = 3000
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    headers = {}
