// Font sans-serif
import '@fontsource/epilogue/100.css'
import '@fontsource/epilogue/200.css'
import '@fontsource/epilogue/300.css'
import '@fontsource/epilogue/400.css'
import '@fontsource/epilogue/500.css'
import '@fontsource/epilogue/600.css'
import '@fontsource/epilogue/700.css'
import '@fontsource/epilogue/800.css'
import '@fontsource/epilogue/900.css'
// Font monospace
import '@fontsource/jetbrains-mono/100.css'
import '@fontsource/jetbrains-mono/200.css'
import '@fontsource/jetbrains-mono/300.css'
import '@fontsource/jetbrains-mono/400.css'
import '@fontsource/jetbrains-mono/500.css'
import '@fontsource/jetbrains-mono/600.css'
import '@fontsource/jetbrains-mono/700.css'
import '@fontsource/jetbrains-mono/800.css'
