name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write # Needed for auth with Deno Deploy
  contents: read # Needed to clone the repository

jobs:
  deploy:
    name: Deploy to Deno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run actions/setup-sdk@local
        uses: ./.github/setup-sdk
        with:
          nodeVersion: lts/*

      - if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build the application
        run: |
          pnpm run build
          echo "BUILD_SUCCESS=$([ -d ".next" ] && echo "true" || echo "false")" >> $GITHUB_ENV

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        if: env.BUILD_SUCCESS == 'true'
        with:
          project: 'next-start' # Your project name
          entrypoint: "jsr:@deno/nextjs-start"
          root: "."
          include: .next, public
